services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notestats-web
    expose:
      - "5004"
    ports:
      - "5004:5004"
    restart: always
    environment:
      - PORT=5004
      - USING_DOCKER=true
    env_file:
      - .env
    depends_on:
      - postgres

  weather-scraper:
    build:
      context: .
    container_name: weather-scraper
    restart: always
    working_dir: /app
    command: "npm run scraper"
    depends_on:
      - app
      - postgres

  postgres:
    image: postgres:14
    container_name: notestats-postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: