services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: graphsfm-backend
    expose:
      - "5000"  # expose to containers internal network
    restart: always
    environment:
      - PORT=500
      - NODE_ENV=production
    env_file:
      - .env
      - ./backend/.env # includes backend specific variables, such as api credentials and token secrets

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: graphsfm-frontend
    expose:
      - "3000" # expose to containers internal network
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    env_file:
      - ./frontend/.env


  cron:
    build:
      context: .
      dockerfile: ./cron/Dockerfile
    container_name: graphsfm-cron
    restart: always
    working_dir: /app
    env_file:
      - ./backend/.env
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: graphsfm-nginx
    ports:
      - "5004:80"  # Expose port 5004 to host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  redis:
    image: redis:alpine  # Lightweight Redis image
    container_name: graphsfm-redis
    restart: always
#    ports:
#      - "6379:6379"  # expose redis to the host machine
    volumes:
      - redis_data:/data  # Persistent storage for Redis data
