services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: notestats-backend
    expose:
      - "5000"  # expose to containers internal network
    restart: always
    environment:
      - PORT=500
      - NODE_ENV=production
    env_file:
      - .env
      - ./backend/.env # includes backend specific variables, such as api credentials and token secrets
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: notestats-frontend
    expose:
      - "3000" # expose to containers internal network
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    env_file:
      - ./frontend/.env
    depends_on:
      - postgres

  cron:
    build:
      context: .
      dockerfile: ./cron/Dockerfile
    container_name: notestats-cron
    restart: always
    working_dir: /app
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - postgres

  postgres:
    image: postgres:14
    container_name: notestats-postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: notestats-nginx
    ports:
      - "5004:80"  # Expose port 5004 to host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: